version: '3'

services:

  web:
    image: nginx:1.17-alpine
    volumes:
      - .:/web
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 8089:80
    environment:
      - NGINX_SITE_DOCUMENT_ROOT=/web/public

  php:
    build: docker/php
    depends_on:
      - db
    volumes:
      - .:/web

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      -  3306:3306
    volumes:
      - db-datavolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      -  8080:8080