version: '3'

services:

  web:
    image: nginx:1.17-alpine
    volumes:
      - .:/web
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    ports:
      - 8089:80
    environment:
      - NGINX_SITE_DOCUMENT_ROOT=/web/public

  php:
    build: docker/php
    depends_on:
      - mariadb
    volumes:
      - .:/web

  mariadb:
    image: mariadb:10.3
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
       - mariadb:db
    ports:
       - 8765:80
    environment:
       MYSQL_ROOT_PASSWORD: qwerty
    depends_on:
       - mariadb